### ISSUE TITLE
SRTM terrain?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/map#1]
Is the terrain model in the National Map using this SRTM dataset?
http://opentopo.sdsc.edu/gridsphere/gridsphere?cid=geonlidarframeportlet&gs_action=raster&opentopoID=OTSRTM.042013.4326.1

**Comment by kring** [comment]
It uses STK World Terrain, which includes data from SRTM, NED, and other sources.  Details here:
http://cesiumjs.org/data-and-assets/terrain/stk-world-terrain.html
