### ISSUE TITLE
Misregistered "Cropping Management Practices" layer on Australian National Map

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/map#5]
I don't know if this is a provider issue, or a National Map/TerriaJS issue, but when I selected the `data.gov.au=>Department of Agriculture=>Cropping Management Practices` layer, I got the following map, which is pretty clearly misregistered:

![9-1-2015 9-16-18 am](https://cloud.githubusercontent.com/assets/1872600/9605278/c58f5d40-508a-11e5-9fa8-a4333c4beab9.jpg)

**Comment by kring** [comment]
Thanks for the report @rsignell-usgs.  It looks like it's a problem with the data (or perhaps the data.gov.au hosting of it).  See the data.gov.au preview:
http://www.data.gov.au/dataset/cropping-management-practices-1998-1999/resource/ad9b991a-dbe7-4586-beae-e0d29a11e9d9
I've posted a comment on data.gov.au and will close this issue.
